version: '2'
services:
  postgres:
      image: postgres:9.6
      environment:
          - POSTGRES_USER=dbt
          - POSTGRES_PASSWORD=dbt
          - POSTGRES_DB=dbt
      ports:
          - 5432:5432
      volumes:  # Reuses data from datavault2 example
          - ./examples/datavault2-bigdata-example/setup/100_restore.sql:/docker-entrypoint-initdb.d/100_restore.sql
          - ./examples/datavault2-bigdata-example/setup/200_users.sql:/docker-entrypoint-initdb.d/200_users.sql
          - ./examples/datavault2-bigdata-example/setup/300_fixdata.sql:/docker-entrypoint-initdb.d/300_fixdata.sql
          - ./examples/datavault2-bigdata-example/setup/data:/docker-entrypoint-initdb.d/data
